let UnsplashAuthorizeURLString = "https://unsplash.com/oauth/authorize"
let AccessKey = "XpPomELrVMrC-Nq2rveKG6hdHbH0rMkQnVN4SF5M5vc"
let SecretKey = "lLIDFsCxLBx3_WnRiydhODcF5f9IcqtQ1MQ-IOKDfIk"
let RedirectURI = "urn:ietf:wg:oauth:2.0:oob"
let AccessScope = "public+read_user+write_likes"
